# Generated by Django 4.2.30 on 2026-06-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
        ('clientes', '0003_detalle_cuenta_contable'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_plan_cuentas_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('ajuste', 'Ajuste Contable'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('factura_emitida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='clientes.facturaemitida', verbose_name='Factura Emitida')),
                ('factura_recibida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='proveedores.facturarecibida', verbose_name='Factura Recibida')),
                ('movimiento_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='tesoreria.movimientobancario', verbose_name='Movimiento Bancario')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Haber')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asientocontable', verbose_name='Asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.plancuentas', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_compras_default', models.ForeignKey(blank=True, help_text='Se usa cuando el detalle de factura recibida no tiene cuenta asignada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Costos/Compras por Defecto')),
                ('cuenta_cxc', models.ForeignKey(blank=True, help_text='Cuenta activo para registrar cuentas por cobrar (Debe en venta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta CxC (Clientes Nacionales)')),
                ('cuenta_cxp', models.ForeignKey(blank=True, help_text='Cuenta pasivo para registrar cuentas por pagar (Haber en compra).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta CxP (Facturas por Pagar)')),
                ('cuenta_iva_credito', models.ForeignKey(blank=True, help_text='Cuenta activo IVA en compras.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='IVA Crédito Fiscal')),
                ('cuenta_iva_debito', models.ForeignKey(blank=True, help_text='Cuenta pasivo IVA en ventas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='IVA Débito Fiscal')),
                ('cuenta_ventas_default', models.ForeignKey(blank=True, help_text='Se usa cuando el detalle de factura no tiene cuenta asignada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Ingresos por Defecto')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuración Contable',
            },
        ),
    ]
