# Generated by Django 4.2.30 on 2026-06-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_libro_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_sueldos',
            field=models.ForeignKey(blank=True, help_text='Cuenta gasto para registrar el pago de remuneraciones (Debe en pago).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Sueldos y Remuneraciones'),
        ),
    ]
