# Generated by Django 4.2.30 on 2026-06-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_add_cuenta_sueldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_impuestos_sii',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para registrar obligaciones tributarias pagadas al SII (Debe en pago F29).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Impuestos SII (F29 / PPM)'),
        ),
    ]
