# Generated by Django 4.2.30 on 2026-06-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_add_cuenta_impuestos_sii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncontable',
            name='cuenta_sueldos',
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_sueldos_administrativo',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto para remuneraciones del personal administrativo (DEBE en pago).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Sueldos — Gasto Administrativo'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_sueldos_operacional',
            field=models.ForeignKey(blank=True, help_text='Cuenta de costo para remuneraciones del personal operativo (DEBE en pago).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Sueldos — Costo Operacional'),
        ),
    ]
