# Generated by Django 4.2.30 on 2026-06-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_alter_detallerendicion_n_boleta_factura'),
        ('contabilidad', '0007_centrocosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='rendicion_gastos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='proveedores.rendiciongastos', verbose_name='Rendición de Gastos'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo'),
        ),
    ]
