# Generated by Django 4.2.30 on 2026-06-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_asientocontable_rendicion_gastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_afp_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para el descuento AFP retenido al trabajador pendiente de enterar a la AFP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='AFP por Pagar'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_salud_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para el descuento de salud retenido al trabajador pendiente de enterar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Salud por Pagar (Isapre/FONASA)'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_sueldos_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo catch-all para otros descuentos y anticipos descontados en liquidación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Sueldos por Pagar (otros descuentos)'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('pago_remuneracion', 'Pago de Remuneración'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo'),
        ),
    ]
