# Generated by Django 4.2.30 on 2026-06-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_configuracioncontable_cuenta_anticipos_trabajadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_anticipos_proveedores',
            field=models.ForeignKey(blank=True, help_text='Cuenta activo para registrar anticipos entregados a proveedores pendientes de aplicar contra factura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Anticipos a Proveedores'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
    ]
