# Generated by Django 4.2.30 on 2026-06-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_trabajador_exento_previsional'),
        ('contabilidad', '0012_configuracioncontable_cuenta_patrimonio_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='remuneracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='rrhh.remuneracion', verbose_name='Remuneración'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Asiento de Apertura'), ('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('devengamiento_remuneracion', 'Devengamiento de Remuneración'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('ingreso', 'Ingreso'), ('costo', 'Costo Operacional'), ('gasto', 'Gasto Administrativo'), ('socio', 'Socio / Gerencia'), ('patrimonio', 'Patrimonio / Resultados Acumulados')], max_length=20, verbose_name='Tipo'),
        ),
    ]
