# Generated by Django 4.2.30 on 2026-06-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_asiento_devengamiento_remuneracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaasiento',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_asiento', to='contabilidad.centrocosto', verbose_name='Centro de Costo'),
        ),
    ]
