# Generated by Django 4.2.30 on 2026-06-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
        ('contabilidad', '0016_asientocontable_nota_credito_recibida'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='boleta_honorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='boletas.boletahonorarios', verbose_name='Boleta de Honorarios'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_honorarios_default',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto/costo usada cuando una boleta de honorarios no tiene cuenta asignada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Honorarios por Defecto'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_retenciones_honorarios',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para registrar la retención de boletas de honorarios pendiente de enterar al SII.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Retenciones Honorarios por Pagar'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Asiento de Apertura'), ('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('nota_credito_compra', 'Nota de Crédito de Compra'), ('boleta_honorarios', 'Boleta de Honorarios'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('devengamiento_remuneracion', 'Devengamiento de Remuneración'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
    ]
