# Generated by Django 4.2.30 on 2026-07-02 20:45

from django.db import migrations, models
import django.db.models.deletion


def configurar_cuenta_ppm_existente(apps, schema_editor):
    ConfiguracionContable = apps.get_model('contabilidad', 'ConfiguracionContable')
    PlanCuentas = apps.get_model('contabilidad', 'PlanCuentas')

    cuenta_ppm = PlanCuentas.objects.filter(
        nombre__iexact='PPM',
        tipo='activo',
        activa=True,
    ).first()
    if cuenta_ppm:
        ConfiguracionContable.objects.filter(pk=1, cuenta_ppm__isnull=True).update(
            cuenta_ppm=cuenta_ppm
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0002_registrocompra_nota_credito'),
        ('contabilidad', '0019_asientocontable_declaracion_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='formulario_f29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='tributario.formulariof29', verbose_name='Formulario F29'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_ppm',
            field=models.ForeignKey(blank=True, help_text='Cuenta activo para registrar los pagos provisionales mensuales entregados al SII.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='PPM por Recuperar'),
        ),
        migrations.RunPython(
            configurar_cuenta_ppm_existente,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Asiento de Apertura'), ('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('nota_credito_compra', 'Nota de Crédito de Compra'), ('boleta_honorarios', 'Boleta de Honorarios'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('devengamiento_remuneracion', 'Devengamiento de Remuneración'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('centralizacion_iva', 'Centralización de IVA'), ('pago_f29', 'Pago de F29'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='configuracioncontable',
            name='cuenta_impuestos_sii',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para registrar obligaciones tributarias pagadas al SII (Debe en pago F29).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Cuenta Impuestos SII (F29)'),
        ),
    ]
