# Generated by Django 4.2.30 on 2026-07-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0003_alter_ppm_estado'),
        ('contabilidad', '0020_asientocontable_formulario_f29_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='ppm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='tributario.ppm', verbose_name='PPM'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Asiento de Apertura'), ('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('nota_credito_compra', 'Nota de Crédito de Compra'), ('boleta_honorarios', 'Boleta de Honorarios'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('devengamiento_remuneracion', 'Devengamiento de Remuneración'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('centralizacion_iva', 'Centralización de IVA'), ('devengamiento_ppm', 'Devengamiento de PPM'), ('pago_f29', 'Pago de F29'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
    ]
