# Generated by Django 4.2.30 on 2026-07-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_remuneracion_seguro_cesantia_empleador_and_more'),
        ('contabilidad', '0021_asientocontable_ppm_alter_asientocontable_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='declaracion_previsional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='rrhh.declaracionprevisional', verbose_name='Declaración Previsional'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_gasto_seguro_cesantia',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto o costo para la cotización de cesantía de cargo del empleador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Gasto Seguro de Cesantía Empleador'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuenta_seguro_cesantia_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Cuenta pasivo para las cotizaciones de cesantía del trabajador y empleador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.plancuentas', verbose_name='Seguro de Cesantía por Pagar'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Asiento de Apertura'), ('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Compra'), ('nota_credito_compra', 'Nota de Crédito de Compra'), ('boleta_honorarios', 'Boleta de Honorarios'), ('pago_cxc', 'Cobro CxC'), ('pago_cxp', 'Pago CxP'), ('movimiento_banco', 'Movimiento Bancario'), ('devengamiento_remuneracion', 'Devengamiento de Remuneración'), ('pago_remuneracion', 'Pago de Remuneración'), ('pago_previsional', 'Pago de Obligaciones Previsionales'), ('pago_anticipo', 'Pago de Anticipo Laboral'), ('pago_anticipo_proveedor', 'Pago de Anticipo a Proveedor'), ('centralizacion_iva', 'Centralización de IVA'), ('devengamiento_ppm', 'Devengamiento de PPM'), ('pago_f29', 'Pago de F29'), ('ajuste', 'Ajuste Contable'), ('rendicion_gastos', 'Rendición de Gastos'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo'),
        ),
    ]
