# Generated by Django 4.2.30 on 2026-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='app_permisos',
            field=models.JSONField(blank=True, default=list, verbose_name='Permisos de aplicaciones'),
        ),
    ]
