# Generated by Django 4.2.30 on 2026-07-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_app_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firma',
            field=models.ImageField(blank=True, help_text='Se recomienda una imagen PNG con fondo transparente.', null=True, upload_to='usuarios/firmas/', verbose_name='Firma'),
        ),
    ]
