# Generated by Django 4.2.30 on 2026-06-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/', verbose_name='Foto')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en sitio')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Ej: bi-tools, bi-house, bi-brush', max_length=50, verbose_name='Icono Bootstrap Icons')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en sitio')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('muebles', 'Muebles'), ('terminaciones', 'Terminaciones'), ('cocinas', 'Cocinas'), ('closets', 'Closets'), ('oficinas', 'Oficinas'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('imagen_principal', models.ImageField(upload_to='portafolio/', verbose_name='Imagen Principal')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en inicio')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en sitio')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de aparición')),
                ('proyecto_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto interno relacionado')),
            ],
            options={
                'verbose_name': 'Proyecto Portafolio',
                'verbose_name_plural': 'Proyectos Portafolio',
                'ordering': ['orden', '-creado_en'],
            },
        ),
    ]
