# Generated by Django 4.2.30 on 2026-06-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_proyectoimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_sitio', models.CharField(default='STA Muebles y Terminaciones', max_length=150, verbose_name='Nombre del sitio')),
                ('meta_descripcion', models.TextField(blank=True, default='STA Muebles y Terminaciones - Calidad en cada detalle', verbose_name='Meta descripción global')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='web/logo/', verbose_name='Logo')),
                ('descripcion_footer', models.TextField(blank=True, default='Muebles y Terminaciones de calidad para proyectos residenciales y comerciales en Chile.', verbose_name='Descripción del footer')),
                ('telefono', models.CharField(blank=True, default='+56 X XXXX XXXX', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='contacto@stamuebles.cl', max_length=254, verbose_name='Email')),
                ('ubicacion', models.CharField(blank=True, default='Chile', max_length=200, verbose_name='Ubicación')),
                ('horario_atencion', models.CharField(blank=True, default='Lun-Vie: 8:30-18:00', max_length=150, verbose_name='Horario de atención')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='PaginaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('inicio', 'Inicio'), ('proyectos', 'Proyectos'), ('servicios', 'Servicios'), ('nosotros', 'Nosotros'), ('contacto', 'Contacto'), ('contacto_gracias', 'Contacto - Gracias')], max_length=50, unique=True, verbose_name='Página')),
                ('nombre_url', models.CharField(blank=True, help_text='Ej: web:index', max_length=80, verbose_name='Nombre URL')),
                ('titulo_navegador', models.CharField(blank=True, max_length=200, verbose_name='Título del navegador')),
                ('meta_descripcion', models.TextField(blank=True, verbose_name='Meta descripción')),
                ('titulo_menu', models.CharField(blank=True, max_length=80, verbose_name='Texto de menú')),
                ('titulo_encabezado', models.CharField(blank=True, max_length=200, verbose_name='Título de encabezado')),
                ('subtitulo_encabezado', models.TextField(blank=True, verbose_name='Subtítulo de encabezado')),
                ('imagen_encabezado', models.ImageField(blank=True, null=True, upload_to='web/paginas/', verbose_name='Imagen de encabezado')),
                ('mostrar_en_menu', models.BooleanField(default=True, verbose_name='Mostrar en menú')),
                ('mostrar_en_footer', models.BooleanField(default=True, verbose_name='Mostrar en footer')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Página Web',
                'verbose_name_plural': 'Páginas Web',
                'ordering': ['orden', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SeccionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.SlugField(help_text='Identificador usado por la plantilla. Ej: hero, estadisticas, cta', max_length=80, verbose_name='Clave')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='web/secciones/', verbose_name='Imagen')),
                ('icono', models.CharField(blank=True, help_text='Ej: bi-tools', max_length=50, verbose_name='Icono Bootstrap')),
                ('texto_boton', models.CharField(blank=True, max_length=80, verbose_name='Texto botón')),
                ('url_boton', models.CharField(blank=True, help_text='Ej: /contacto/', max_length=200, verbose_name='URL botón')),
                ('texto_boton_secundario', models.CharField(blank=True, max_length=80, verbose_name='Texto botón secundario')),
                ('url_boton_secundario', models.CharField(blank=True, help_text='Ej: /proyectos/', max_length=200, verbose_name='URL botón secundario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='web.paginaweb', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Sección Web',
                'verbose_name_plural': 'Secciones Web',
                'ordering': ['pagina', 'orden', 'clave'],
                'unique_together': {('pagina', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='ItemSeccionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('valor', models.CharField(blank=True, max_length=50, verbose_name='Valor destacado')),
                ('icono', models.CharField(blank=True, help_text='Ej: bi-award', max_length=50, verbose_name='Icono Bootstrap')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='web/items/', verbose_name='Imagen')),
                ('enlace', models.CharField(blank=True, max_length=200, verbose_name='Enlace')),
                ('texto_enlace', models.CharField(blank=True, max_length=80, verbose_name='Texto enlace')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.seccionweb', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Ítem de Sección',
                'verbose_name_plural': 'Ítems de Sección',
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
    ]
