# Generated by Django 4.2.30 on 2026-06-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_precargar_contenido_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
            ],
            options={
                'verbose_name': 'Portada principal',
                'verbose_name_plural': 'Portada principal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.seccionweb',),
        ),
    ]
