# Generated by Django 4.2.30 on 2026-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion_empresa',
            field=models.CharField(default='SIMPSON 46, CHILLÁN', max_length=300, verbose_name='Dirección empresa'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='giro_empresa',
            field=models.CharField(default='Soluciones termoacústicas, muebles y terminaciones', max_length=250, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='razon_social',
            field=models.CharField(default='SOLUCIONES TERMO ACUSTICAS SPA', max_length=200, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='rut_empresa',
            field=models.CharField(default='76.471.912-3', max_length=15, verbose_name='RUT empresa'),
        ),
    ]
