# Generated by Django 4.2.30 on 2026-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_configuracionsitio_direccion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='firma_representante_legal',
            field=models.ImageField(blank=True, help_text='Se recomienda una imagen PNG con fondo transparente.', null=True, upload_to='web/empresa/firmas/', verbose_name='Firma del representante legal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante legal'),
        ),
    ]
