# Generated by Django 4.2.30 on 2026-06-02 20:39

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=15, unique=True, validators=[apps.core.validators.validar_rut], verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Base')),
                ('afp', models.CharField(blank=True, max_length=100, verbose_name='AFP')),
                ('isapre', models.CharField(blank=True, max_length=100, verbose_name='Isapre/FONASA')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='N° Cuenta Bancaria')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Con Licencia'), ('vacaciones', 'En Vacaciones')], default='activo', max_length=15, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('cambio_cargo', 'Cambio de Cargo'), ('cambio_sueldo', 'Cambio de Sueldo'), ('licencia', 'Licencia Médica'), ('vacaciones', 'Vacaciones'), ('amonestacion', 'Amonestación'), ('finiquito', 'Finiquito'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rrhh.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Historial Laboral',
                'verbose_name_plural': 'Historial Laboral',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AnticipoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('descontado', 'Descontado en liquidación')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='rrhh.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Anticipo Laboral',
                'verbose_name_plural': 'Anticipos Laborales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Base')),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Extra')),
                ('bono', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonos')),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Bruto')),
                ('descuento_afp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento AFP')),
                ('descuento_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Salud')),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros Descuentos')),
                ('anticipo_descontado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Anticipo Descontado')),
                ('liquido_pagar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Líquido a Pagar')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado')], default='borrador', max_length=10, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remuneraciones', to='rrhh.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Remuneración',
                'verbose_name_plural': 'Remuneraciones',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('trabajador', 'periodo_mes', 'periodo_anio')},
            },
        ),
    ]
