# Generated by Django 4.2.30 on 2026-06-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='tipo_costo',
            field=models.CharField(choices=[('operacional', 'Costo Operacional'), ('administrativo', 'Gasto Administrativo')], default='administrativo', help_text='Determina la cuenta contable usada al pagar remuneraciones y anticipos.', max_length=15, verbose_name='Tipo de costo'),
        ),
    ]
