# Generated by Django 4.2.30 on 2026-06-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_libro_diario'),
        ('rrhh', '0002_trabajador_tipo_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='afp',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('cuprum', 'Cuprum'), ('habitat', 'Hábitat'), ('modelo', 'Modelo'), ('planvital', 'PlanVital'), ('provida', 'Provida'), ('uno', 'Uno')], max_length=100, verbose_name='AFP'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.banco', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='isapre',
            field=models.CharField(blank=True, choices=[('colmena', 'Colmena'), ('consalud', 'Consalud'), ('cruz_blanca', 'Cruz Blanca'), ('fonsalud', 'FONASA'), ('fundacion', 'Fundación'), ('masvida', 'Masvida'), ('nueva_masvida', 'Nueva Masvida'), ('red_salud', 'Red Salud'), ('vida_chile', 'Vida Chile')], max_length=100, verbose_name='Isapre/FONASA'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('vista', 'Cuenta Vista'), ('rut', 'Cuenta RUT')], max_length=50, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='rrhh.cargotrabajador', verbose_name='Cargo'),
        ),
    ]
