# Generated by Django 4.2.30 on 2026-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_cargotrabajador_alter_trabajador_afp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
