# Generated by Django 4.2.30 on 2026-06-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_trabajador_centro_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='foto',
        ),
    ]
