# Generated by Django 4.2.30 on 2026-06-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_remove_trabajador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='exento_previsional',
            field=models.BooleanField(default=False, help_text='Marcar si el trabajador no tiene contrato y solo se le paga el sueldo bruto sin descuentos previsionales.', verbose_name='Exento de AFP/Salud'),
        ),
    ]
