# Generated by Django 4.2.30 on 2026-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_trabajador_exento_previsional'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='impuesto_unico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto Único'),
        ),
    ]
