# Generated by Django 4.2.30 on 2026-07-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_movimientobancario_conciliado_por_and_more'),
        ('rrhh', '0010_remuneracion_fecha_devengamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipolaboral',
            name='movimiento_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anticipo_laboral', to='tesoreria.movimientobancario', verbose_name='Movimiento de pago'),
        ),
    ]
