# Generated by Django 4.2.30 on 2026-07-03 13:40

from django.db import migrations, models
import django.db.models.deletion


def vincular_movimientos_pago_existentes(apps, schema_editor):
    Remuneracion = apps.get_model('rrhh', 'Remuneracion')
    AsientoContable = apps.get_model('contabilidad', 'AsientoContable')
    remuneraciones_vinculadas = set()
    movimientos_usados = set()

    relaciones = AsientoContable.objects.filter(
        tipo='pago_remuneracion',
        remuneracion_id__isnull=False,
        movimiento_bancario_id__isnull=False,
    ).order_by('-id').values_list(
        'remuneracion_id',
        'movimiento_bancario_id',
    )
    for remuneracion_id, movimiento_id in relaciones:
        if (
            remuneracion_id in remuneraciones_vinculadas
            or movimiento_id in movimientos_usados
        ):
            continue
        actualizado = Remuneracion.objects.filter(
            pk=remuneracion_id,
            movimiento_pago_id__isnull=True,
        ).update(movimiento_pago_id=movimiento_id)
        if actualizado:
            remuneraciones_vinculadas.add(remuneracion_id)
            movimientos_usados.add(movimiento_id)


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_asientocontable_ppm_alter_asientocontable_tipo'),
        ('tesoreria', '0004_movimientobancario_conciliado_por_and_more'),
        ('rrhh', '0011_alter_anticipolaboral_movimiento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='movimiento_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remuneracion_pagada', to='tesoreria.movimientobancario', verbose_name='Movimiento de pago'),
        ),
        migrations.RunPython(
            vincular_movimientos_pago_existentes,
            migrations.RunPython.noop,
        ),
    ]
