# Generated by Django 4.2.30 on 2026-07-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_movimientobancario_conciliado_por_and_more'),
        ('rrhh', '0012_remuneracion_movimiento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='seguro_cesantia_empleador',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Seguro de Cesantía — Empleador'),
        ),
        migrations.AddField(
            model_name='remuneracion',
            name='seguro_cesantia_trabajador',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Seguro de Cesantía — Trabajador'),
        ),
        migrations.CreateModel(
            name='DeclaracionPrevisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('total_afp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_salud', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cesantia_trabajador', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cesantia_empleador', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('presentada', 'Presentada'), ('pagada', 'Pagada')], default='borrador', max_length=12)),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=80)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('movimiento_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaracion_previsional', to='tesoreria.movimientobancario', verbose_name='Movimiento de pago')),
                ('remuneraciones', models.ManyToManyField(blank=True, related_name='declaraciones_previsionales', to='rrhh.remuneracion', verbose_name='Remuneraciones incluidas')),
            ],
            options={
                'verbose_name': 'Declaración Previsional',
                'verbose_name_plural': 'Declaraciones Previsionales',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.AddConstraint(
            model_name='declaracionprevisional',
            constraint=models.UniqueConstraint(fields=('periodo_mes', 'periodo_anio'), name='rrhh_declaracion_previsional_periodo_unico'),
        ),
        migrations.AddConstraint(
            model_name='declaracionprevisional',
            constraint=models.CheckConstraint(check=models.Q(('periodo_mes__gte', 1), ('periodo_mes__lte', 12)), name='rrhh_declaracion_previsional_mes_valido'),
        ),
    ]
