# Generated by Django 4.2.30 on 2026-07-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalizar_rut(valor):
    return ''.join(caracter for caracter in (valor or '').upper() if caracter.isalnum())


def asociar_usuarios_existentes(apps, schema_editor):
    Trabajador = apps.get_model('rrhh', 'Trabajador')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    usuarios = list(User.objects.all())
    usuarios_por_rut = {}
    usuarios_por_email = {}
    for usuario in usuarios:
        rut = normalizar_rut(usuario.username)
        if rut:
            usuarios_por_rut.setdefault(rut, []).append(usuario)
        email = (usuario.email or '').strip().lower()
        if email:
            usuarios_por_email.setdefault(email, []).append(usuario)

    usuarios_asignados = set()
    for trabajador in Trabajador.objects.all():
        candidatos = usuarios_por_rut.get(normalizar_rut(trabajador.rut), [])
        if len(candidatos) != 1:
            email = (trabajador.email or '').strip().lower()
            candidatos = usuarios_por_email.get(email, []) if email else []
        if len(candidatos) == 1 and candidatos[0].pk not in usuarios_asignados:
            trabajador.usuario_id = candidatos[0].pk
            trabajador.save(update_fields=['usuario'])
            usuarios_asignados.add(candidatos[0].pk)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0013_remuneracion_seguro_cesantia_empleador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario que podrá ver y crear las rendiciones de este trabajador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.RunPython(asociar_usuarios_existentes, migrations.RunPython.noop),
    ]
