# Generated by Django 4.2.30 on 2026-06-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Neto')),
                ('iva_debito', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='IVA Débito Fiscal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.facturaemitida', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Registro de Venta',
                'verbose_name_plural': 'Registro de Ventas',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Neto')),
                ('iva_credito', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='IVA Crédito Fiscal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.facturarecibida', verbose_name='Factura')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registro de Compras',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Imponible')),
                ('tasa', models.DecimalField(decimal_places=4, default=0.0025, max_digits=5, verbose_name='Tasa PPM')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto PPM')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'PPM',
                'verbose_name_plural': 'PPM',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('periodo_mes', 'periodo_anio')},
            },
        ),
        migrations.CreateModel(
            name='FormularioF29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('iva_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA a Pagar')),
                ('ppm_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPM a Pagar')),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retenciones')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total a Pagar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('presentado', 'Presentado'), ('pagado', 'Pagado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('folio', models.CharField(blank=True, max_length=20, verbose_name='N° Folio')),
            ],
            options={
                'verbose_name': 'Formulario F29',
                'verbose_name_plural': 'Formularios F29',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('periodo_mes', 'periodo_anio')},
            },
        ),
        migrations.CreateModel(
            name='DeclaracionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('iva_debito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA Débito')),
                ('iva_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA Crédito')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diferencia (a pagar)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('presentado', 'Presentado'), ('pagado', 'Pagado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
            ],
            options={
                'verbose_name': 'Declaración IVA',
                'verbose_name_plural': 'Declaraciones IVA',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('periodo_mes', 'periodo_anio')},
            },
        ),
    ]
