# Generated by Django 4.2.30 on 2026-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0002_registrocompra_nota_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppm',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('presentado', 'Presentado'), ('pagado', 'Pagado')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
