# Generated by Django 4.2.30 on 2026-06-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del Proyecto')),
                ('estado', models.CharField(choices=[('negociacion', 'En Negociación'), ('adjudicado', 'Adjudicado'), ('en_ejecucion', 'En Ejecución'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='negociacion', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('monto_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Contrato')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion_obra', models.CharField(blank=True, max_length=300, verbose_name='Dirección de la Obra')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en portafolio')),
                ('mostrar_en_web', models.BooleanField(default=False, verbose_name='Mostrar en sitio web')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=200, verbose_name='Ítem')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de Obra'), ('subcontrato', 'Subcontrato'), ('equipo', 'Equipos/Herramientas'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Presupuestado')),
                ('monto_real', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Real')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['proyecto', 'item'],
            },
        ),
        migrations.CreateModel(
            name='CostoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de Obra'), ('subcontrato', 'Subcontrato'), ('equipo', 'Equipos/Herramientas'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta contable')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.facturarecibida', verbose_name='Factura relacionada')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Costo de Proyecto',
                'verbose_name_plural': 'Costos de Proyectos',
                'ordering': ['-fecha'],
            },
        ),
    ]
