# Generated by Django 4.2.30 on 2026-06-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_costoproyecto_centro_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
    ]
