# Generated by Django 4.2.30 on 2026-06-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('tipo', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('vista', 'Cuenta Vista'), ('rut', 'Cuenta RUT')], default='corriente', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo inicial')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.banco', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'unique_together': {('banco', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('documento', models.CharField(blank=True, max_length=50, verbose_name='N° Documento')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuentabancaria', verbose_name='Cuenta bancaria')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta contable')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
