# Generated by Django 4.2.30 on 2026-06-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_libro_diario'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta del plan de cuentas que representa esta cuenta bancaria.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta Contable'),
        ),
    ]
