# Generated by Django 4.2.30 on 2026-06-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_fecha_conciliacion(apps, schema_editor):
    MovimientoBancario = apps.get_model('tesoreria', 'MovimientoBancario')
    for movimiento in MovimientoBancario.objects.filter(conciliado=True, fecha_conciliacion__isnull=True):
        movimiento.fecha_conciliacion = movimiento.fecha
        movimiento.save(update_fields=['fecha_conciliacion'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesoreria', '0003_cargar_bancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='conciliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_conciliados', to=settings.AUTH_USER_MODEL, verbose_name='Conciliado por'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de conciliación'),
        ),
        migrations.RunPython(backfill_fecha_conciliacion, migrations.RunPython.noop),
    ]
