# Generated by Django 4.2.30 on 2026-07-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_movimientobancario_conciliado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se recomienda una imagen PNG o WebP con fondo transparente.', null=True, upload_to='tesoreria/bancos/logos/', verbose_name='Logo'),
        ),
    ]
