# Generated by Django 4.2.30 on 2026-06-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_plan_cuentas_inicial'),
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaemitida',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta contable'),
        ),
    ]
