# Generated by Django 4.2.30 on 2026-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_detalle_cuenta_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='medio_cobro',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=20, verbose_name='Medio de Cobro'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='N° transferencia, cheque, depósito, etc.', max_length=100, verbose_name='N° Documento / Referencia'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cobro'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Cobrado'),
        ),
    ]
