# Generated by Django 4.2.30 on 2026-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_centrocosto'),
        ('clientes', '0004_cxc_medio_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaemitida',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de Costo'),
        ),
    ]
