# Generated by Django 4.2.30 on 2026-06-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0003_cargar_bancos'),
        ('clientes', '0005_detallefacturaemitida_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='movimiento_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobrar', to='tesoreria.movimientobancario', verbose_name='Movimiento de Cobro'),
        ),
    ]
