# Generated by Django 4.2.30 on 2026-06-02 20:39

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Anticipo a Proveedor',
                'verbose_name_plural': 'Anticipos a Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Pagado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaRecibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Detalle Factura Recibida',
                'verbose_name_plural': 'Detalles Facturas Recibidas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=15, unique=True, validators=[apps.core.validators.validar_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('giro', models.CharField(blank=True, max_length=200, verbose_name='Giro')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Nombre contacto')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='N° Cuenta bancaria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='FacturaRecibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, verbose_name='N° Factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Neto')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='IVA (19%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Factura Recibida',
                'verbose_name_plural': 'Facturas Recibidas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
