# Generated by Django 4.2.30 on 2026-06-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturarecibida',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='detallefacturarecibida',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta contable'),
        ),
        migrations.AddField(
            model_name='detallefacturarecibida',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.facturarecibida', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_pagar', to='proveedores.facturarecibida', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='facturarecibida',
            unique_together={('proveedor', 'numero')},
        ),
    ]
