# Generated by Django 4.2.30 on 2026-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('debito', 'Débito automático'), ('otro', 'Otro')], max_length=20, verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de cheque, folio transferencia, etc.', max_length=100, verbose_name='Nº Documento / Referencia'),
        ),
    ]
