# Generated by Django 4.2.30 on 2026-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_cxp_medio_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturarecibida',
            name='monto',
        ),
        migrations.AddField(
            model_name='detallefacturarecibida',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='detallefacturarecibida',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15, verbose_name='Precio Unitario'),
            preserve_default=False,
        ),
    ]
