# Generated by Django 4.2.30 on 2026-06-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_libro_diario'),
        ('proveedores', '0004_remove_detallefacturarecibida_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.banco', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('vista', 'Cuenta Vista'), ('rut', 'Cuenta RUT')], max_length=50, verbose_name='Tipo de cuenta'),
        ),
    ]
