# Generated by Django 4.2.30 on 2026-06-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_centrocosto'),
        ('proveedores', '0005_alter_proveedor_banco_alter_proveedor_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturarecibida',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de Costo'),
        ),
    ]
