# Generated by Django 4.2.30 on 2026-06-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_remove_trabajador_foto'),
        ('contabilidad', '0007_centrocosto'),
        ('proveedores', '0007_remove_facturarecibida_centro_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_pagar', to='proveedores.facturarecibida', verbose_name='Factura'),
        ),
        migrations.CreateModel(
            name='RendicionGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha de Rendición')),
                ('motivo_del_gasto', models.CharField(max_length=300, verbose_name='Motivo del gasto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones', to='rrhh.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Rendición de Gastos',
                'verbose_name_plural': 'Rendiciones de Gastos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha del gasto')),
                ('n_boleta_factura', models.CharField(blank=True, max_length=100, verbose_name='N° Boleta o Factura')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto del gasto')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de Costo')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta contable')),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.rendiciongastos', verbose_name='Rendición de Gastos')),
            ],
            options={
                'verbose_name': 'Detalle de Rendición',
                'verbose_name_plural': 'Detalles de Rendiciones',
            },
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='rendicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_pagar', to='proveedores.rendiciongastos', verbose_name='Rendición de Gastos'),
        ),
    ]
