# Generated by Django 4.2.30 on 2026-06-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_cuentaporpagar_factura_rendiciongastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerendicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
