# Generated by Django 4.2.30 on 2026-06-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_proyecto_imagen'),
        ('proveedores', '0009_detallerendicion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciongastos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
    ]
