# Generated by Django 4.2.30 on 2026-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_rendiciongastos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerendicion',
            name='n_boleta_factura',
            field=models.CharField(max_length=100, verbose_name='N° Boleta o Factura'),
        ),
    ]
