# Generated by Django 4.2.30 on 2026-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_alter_detallerendicion_n_boleta_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciongastos',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado para revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=15, verbose_name='Estado'),
        ),
    ]
