# Generated by Django 4.2.30 on 2026-06-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0012_rendiciongastos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturarecibida',
            name='exento_iva',
            field=models.BooleanField(default=False, verbose_name='Exento de IVA'),
        ),
    ]
