# Generated by Django 4.2.30 on 2026-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_detallefacturarecibida_exento_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturarecibida',
            name='exento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Exento'),
        ),
        migrations.AlterField(
            model_name='facturarecibida',
            name='neto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Neto Afecto'),
        ),
    ]
