# Generated by Django 4.2.30 on 2026-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0016_add_movimiento_pago_to_cxp_cxc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturarecibida',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallefacturarecibida',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Precio Unitario'),
        ),
    ]
