# Generated by Django 4.2.30 on 2026-06-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
        ('proveedores', '0020_facturarecibida_correlativo_libro_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='boleta_honorarios',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_pagar', to='boletas.boletahonorarios', verbose_name='Boleta de Honorarios'),
        ),
    ]
