# Generated by Django 4.2.30 on 2026-06-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_boleta_honorarios_and_more'),
        ('proveedores', '0021_cuentaporpagar_boleta_honorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturarecibida',
            name='asiento_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_apertura', to='contabilidad.asientocontable', verbose_name='Asiento de apertura'),
        ),
        migrations.AddField(
            model_name='facturarecibida',
            name='origen',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('apertura', 'Saldo de apertura')], default='operacional', max_length=20, verbose_name='Origen'),
        ),
    ]
