# Generated by Django 4.2.30 on 2026-06-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0023_anticipo_asiento_apertura_anticipo_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='nota_credito_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anticipo_generado', to='proveedores.notacreditorecibida', verbose_name='Nota de crédito de origen'),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='origen',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('apertura', 'Saldo de apertura'), ('nota_credito', 'Nota de crédito')], default='operacional', max_length=20, verbose_name='Origen'),
        ),
    ]
