# Generated by Django 4.2.30 on 2026-06-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_boleta_honorarios_and_more'),
        ('proveedores', '0024_anticipo_nota_credito_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionAnticipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha de aplicación')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto aplicado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='proveedores.anticipo', verbose_name='Anticipo')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_anticipos_proveedor', to='contabilidad.asientocontable', verbose_name='Asiento contable')),
                ('cuenta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_anticipos', to='proveedores.cuentaporpagar', verbose_name='Cuenta por pagar')),
            ],
            options={
                'verbose_name': 'Aplicación de Anticipo a Proveedor',
                'verbose_name_plural': 'Aplicaciones de Anticipos a Proveedores',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
