# Generated by Django 4.2.30 on 2026-07-08 21:13

from django.db import migrations, models


def completar_periodo_libro_notas_credito(apps, schema_editor):
    NotaCreditoRecibida = apps.get_model('proveedores', 'NotaCreditoRecibida')
    RegistroCompra = apps.get_model('tributario', 'RegistroCompra')

    for nota in NotaCreditoRecibida.objects.only(
        'pk',
        'fecha_emision',
        'periodo_libro_compras_mes',
        'periodo_libro_compras_anio',
    ).iterator():
        if not nota.fecha_emision:
            continue
        periodo_mes = nota.periodo_libro_compras_mes or nota.fecha_emision.month
        periodo_anio = nota.periodo_libro_compras_anio or nota.fecha_emision.year
        NotaCreditoRecibida.objects.filter(pk=nota.pk).update(
            periodo_libro_compras_mes=periodo_mes,
            periodo_libro_compras_anio=periodo_anio,
        )
        RegistroCompra.objects.filter(
            nota_credito_id=nota.pk,
            tipo_documento='nota_credito',
        ).update(
            periodo_mes=periodo_mes,
            periodo_anio=periodo_anio,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0028_recalcular_indice_factura_por_periodo'),
        ('tributario', '0003_alter_ppm_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditorecibida',
            name='periodo_libro_compras_anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año Libro de Compras'),
        ),
        migrations.AddField(
            model_name='notacreditorecibida',
            name='periodo_libro_compras_mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes Libro de Compras'),
        ),
        migrations.RunPython(
            completar_periodo_libro_notas_credito,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='facturarecibida',
            name='periodo_libro_compras_anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año Libro de Compras'),
        ),
        migrations.AlterField(
            model_name='facturarecibida',
            name='periodo_libro_compras_mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes Libro de Compras'),
        ),
    ]
