# Generated by Django 4.2.30 on 2026-07-20 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_proyecto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0022_asientocontable_declaracion_previsional_and_more'),
        ('proveedores', '0029_notacreditorecibida_periodo_libro_compras_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad_medida', models.CharField(choices=[('un', 'Unidad'), ('kg', 'Kilogramo'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('lt', 'Litro'), ('hr', 'Hora'), ('serv', 'Servicio'), ('gl', 'Global')], default='un', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='N° OC')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('proveedor_razon_social', models.CharField(blank=True, max_length=200)),
                ('proveedor_rut', models.CharField(blank=True, max_length=15)),
                ('proveedor_direccion', models.CharField(blank=True, max_length=300)),
                ('proveedor_telefono', models.CharField(blank=True, max_length=20)),
                ('proveedor_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('enviada', 'Enviada'), ('recepcion_parcial', 'Recepción Parcial'), ('recepcion_completa', 'Recepción Completa'), ('facturada', 'Facturada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('condiciones_comerciales', models.TextField(blank=True)),
                ('firma_solicitante', models.ImageField(blank=True, null=True, upload_to='ordenes_compra/firmas/')),
                ('firma_aprobador', models.ImageField(blank=True, null=True, upload_to='ordenes_compra/firmas/')),
                ('fecha_solicitud_aprobacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='contabilidad.centrocosto', verbose_name='Centro de Costo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='proveedores.ordencompra')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_oc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='proveedores.detalleordencompra')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.recepcionordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.ordencompra'),
        ),
        migrations.AddField(
            model_name='facturarecibida',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AddConstraint(
            model_name='detallerecepcionordencompra',
            constraint=models.UniqueConstraint(fields=('recepcion', 'detalle_orden'), name='uniq_recepcion_detalle_oc'),
        ),
    ]
