# Generated by Django 4.2.30 on 2026-07-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0030_detalleordencompra_ordencompra_recepcionordencompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='firma_aprobador',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='firma_solicitante',
        ),
    ]
