# Generated by Django 4.2.30 on 2026-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0031_remove_ordencompra_firma_aprobador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='firma_aprobador',
            field=models.ImageField(blank=True, null=True, upload_to='ordenes_compra/firmas/'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='firma_solicitante',
            field=models.ImageField(blank=True, null=True, upload_to='ordenes_compra/firmas/'),
        ),
    ]
