# Generated by Django 4.2.30 on 2026-06-24 14:16

import apps.core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0003_remove_proyecto_imagen'),
        ('tesoreria', '0003_cargar_bancos'),
        ('contabilidad', '0016_asientocontable_nota_credito_recibida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorHonorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=15, unique=True, validators=[apps.core.validators.validar_rut], verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('giro', models.CharField(blank=True, max_length=200, verbose_name='Giro')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('vista', 'Cuenta Vista'), ('rut', 'Cuenta RUT')], max_length=50, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='N° Cuenta bancaria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.banco', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Prestador de Honorarios',
                'verbose_name_plural': 'Prestadores de Honorarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BoletaHonorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, verbose_name='N° Boleta')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del servicio')),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Bruto')),
                ('tasa_retencion', models.DecimalField(decimal_places=4, default=Decimal('0.1525'), max_digits=6, verbose_name='Tasa Retención')),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retención')),
                ('liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Líquido a pagar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('correlativo_honorarios', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Correlativo Honorarios')),
                ('periodo_honorarios_mes', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Mes Honorarios')),
                ('periodo_honorarios_anio', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Año Honorarios')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de Costo')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.plancuentas', verbose_name='Cuenta de gasto')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas', to='boletas.prestadorhonorarios', verbose_name='Prestador')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Boleta de Honorarios',
                'verbose_name_plural': 'Boletas de Honorarios',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='boletahonorarios',
            constraint=models.UniqueConstraint(fields=('periodo_honorarios_anio', 'periodo_honorarios_mes', 'correlativo_honorarios'), name='uniq_boleta_honorarios_correlativo_mes'),
        ),
        migrations.AlterUniqueTogether(
            name='boletahonorarios',
            unique_together={('prestador', 'numero')},
        ),
    ]
